### ISSUE TITLE
Minimum Cart Subtotal Threshold even if Free Gift is in Cart

### ISSUE THREAD

**Issue by psm9640** [jgodson/shopify-script-creator#107] opened 2024-04-24 19:03 UTC
Hello -

This is most likely due to operator error but I can't seem to figure out a solution and welcome any/all input:

We are using a "Buy X Get X Discounted" script to give someone an item for free if their cart is $99 or more. The free gift is normally $30. The problem is that if the person already has this item in their cart and say the entire value of the cart goes to $105, the discount applied to that free gift knocks the overall cart subtotal to $75. Is a BXGX Discount the wrong application here?

Thank you very much in advance -- script generator has been a life saver thus far!

**Comment by jgodson** [comment] 2024-04-24 19:58
Hey there! Buy X Get X would probably also work fine as long as you add a cart qualifier of "Discounted Cart Subtotal (applied by scripts)". That will ensure that the subtotal is still $99 or more after the discount gets applied. That said, I think a Conditional discount would also work just as well. I have attached screenshots of how you could set that up.

<img width="608" alt="Screenshot 2024-04-24 at 3 55 35 PM" src="https://github.com/jgodson/shopify-script-creator/assets/12747574/fa12585d-9cf8-43a0-9487-fe12295b6608">
<img width="608" alt="Screenshot 2024-04-24 at 3 55 44 PM" src="https://github.com/jgodson/shopify-script-creator/assets/12747574/fd9a95b7-d37e-452f-b0b2-a44bb3545b24">

**Comment by jgodson** [comment] 2024-04-26 13:37
Yep, that should work as long as the discount codes are not for specific products only. There are limitations (or at least there were, not sure if it has changed) on scripts that only allow checking the discount for codes that apply to the entire cart.

**Comment by psm9640** [comment] 2024-04-26 13:56
Thank you Jason!

**Comment by jgodson** [comment] 2024-04-26 13:59
Sorry, I re-read your message and I think you should do the multi select with `All`. `Any` will mean that if it's over $99 after scripts OR over $99 after discounts, but you want it to be both.

**Comment by psm9640** [comment] 2024-06-14 15:35
Hi Jason -

Seeing this issue again despite the change of the conditions to "Meets All". When I test the script in the Shopify script editor and apply a discount code, it's still qualifying the free item even if the subtotal is below $99. Thank you for your insight in advance!

![0614-discount-script](https://github.com/jgodson/shopify-script-creator/assets/10199586/535e7251-e1cc-4b9a-bd13-4512984013e2)

**Comment by jgodson** [comment] 2024-06-17 17:31
@psm9640, curious about the discount code set up. Is it a %, or limited in any way? There are some limitations to what sort of discount codes Shopify Scripts can "see".

**Comment by psm9640** [comment] 2024-06-18 15:27
Hey Jason... This is the setup:

![image](https://github.com/jgodson/shopify-script-creator/assets/10199586/7cfb6064-a931-4a4a-ba0c-6d32c058986a)

There is a rule running simultaneously that makes shipping free if this code is used, but since that's a shipping script I'm not sure that's creating any problems.

**Comment by jgodson** [comment] 2024-06-18 17:06
That does look like it should be ok. I will see if I can find some time to look into this more closely. Thanks for providing the extra information!

**Comment by psm9640** [comment] 2024-06-18 17:53
Thank you Jason -- I really appreciate it!

**Comment by jgodson** [comment] 2024-06-21 11:58
Hey Peter, I looked into this a bit more and I see what the issue is. The discount code one doesn't check the script discount and the script one doesn't check the script discount **combined with** the discount code discount, so they both see the total as being higher than the requirement and the discount applies. I may have to look at adding another option for `Discounted Cart Subtotal (applied by scripts & discount code)` 😄.

**Comment by jgodson** [comment] 2024-06-23 14:38
Hey @psm9640 , I just added what I mentioned above. Let me know if it works!

**Comment by psm9640** [comment] 2024-06-24 19:22
Thank you, Jason - gonna take it for a spin here in a little bit!

**Comment by psm9640** [comment] 2024-07-20 18:07
Hey Jason - I'm not sure if it's a combination of the sales we were doing but everything seemed great for a while with the new additional options but now we're seeing the product tier qualify at lower cart total amounts. Example, current sale is for $89 and above to qualify someone for EAA+, however with the built-in 25% discount (done as a shopify automatic discount), we're getting the following:

![image](https://github.com/user-attachments/assets/b789e8f4-de1a-49db-af96-b9a56d20ac05)

And here's our rule:

![image](https://github.com/user-attachments/assets/5e7185f7-43df-46bb-8f62-af8aa87417df)

I might be missing something but it seems like this should be okay unless we need an additional check for automatic discounts?

Thank you, Jason!

**Comment by jgodson** [comment] 2024-07-23 19:05
@psm9640 Yes, automatic discounts would need another check as they do not show up as discount codes, if I remember correctly. They are applied to the line itself. That said, similar to discount codes that apply to specific items, I'm not sure that the discounts applied by automatic discounts are actually available to be checked in scripts unfortunately. I will try and find some time to verify that though.

**Comment by psm9640** [comment] 2024-08-09 18:21
Sorry for the delay in response. Makes sense! Thank you, Jason!

**Comment by jgodson** [comment] 2024-10-31 12:20
Hey Peter, sorry I never got to checking that, though I am fairly certain that is the case. In any case, with the deprecation of Scripts next August, I'm not planning any new features at this point.

**Closed by jgodson** 2024-10-31 12:20 UTC
